version: "3"

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27021:27017"
    volumes:
      - ./db:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
