version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
      MONGO_URI: mongodb://root:example@mongo/oz-tech-test?authSource=admin
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - mongo-network
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27021:27017"
    volumes:
      - ./db:/data/db
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
